// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.tensunfree.flutter_travel_audio_guide.flutter_travel_audio_guide

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
        listOf(
            exception.code,
            exception.message,
            exception.details
        )
    } else {
        listOf(
            exception.javaClass.simpleName,
            exception.toString(),
            "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
        )
    }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null
) : Throwable()

private open class HealthConnectApiPigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
        return super.readValueOfType(type, buffer)
    }

    override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
        super.writeValue(stream, value)
    }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HealthConnectHostApi {
    fun checkAvailability(callback: (Result<Boolean>) -> Unit)
    fun requestPermissions(callback: (Result<Boolean>) -> Unit)
    fun hasPermissions(callback: (Result<Boolean>) -> Unit)
    fun getStepsBetween(
        startTimeMillis: Long,
        endTimeMillis: Long,
        callback: (Result<Long>) -> Unit
    )

    fun getDistanceBetween(
        startTimeMillis: Long,
        endTimeMillis: Long,
        callback: (Result<Long>) -> Unit
    )

    fun writeExerciseSession(
        guideName: String,
        startTimeMillis: Long,
        endTimeMillis: Long,
        steps: Long,
        distanceCentimetres: Long,
        callback: (Result<Boolean>) -> Unit
    )

    companion object {
        /** The codec used by HealthConnectHostApi. */
        val codec: MessageCodec<Any?> by lazy {
            HealthConnectApiPigeonCodec()
        }

        /** Sets up an instance of `HealthConnectHostApi` to handle messages through the `binaryMessenger`. */
        @JvmOverloads
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: HealthConnectHostApi?,
            messageChannelSuffix: String = ""
        ) {
            val separatedMessageChannelSuffix =
                if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.checkAvailability$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        api.checkAvailability { result: Result<Boolean> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.requestPermissions$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        api.requestPermissions { result: Result<Boolean> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.hasPermissions$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        api.hasPermissions { result: Result<Boolean> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.getStepsBetween$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val startTimeMillisArg = args[0] as Long
                        val endTimeMillisArg = args[1] as Long
                        api.getStepsBetween(
                            startTimeMillisArg,
                            endTimeMillisArg
                        ) { result: Result<Long> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.getDistanceBetween$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val startTimeMillisArg = args[0] as Long
                        val endTimeMillisArg = args[1] as Long
                        api.getDistanceBetween(
                            startTimeMillisArg,
                            endTimeMillisArg
                        ) { result: Result<Long> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.flutter_travel_audio_guide.HealthConnectHostApi.writeExerciseSession$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val guideNameArg = args[0] as String
                        val startTimeMillisArg = args[1] as Long
                        val endTimeMillisArg = args[2] as Long
                        val stepsArg = args[3] as Long
                        val distanceCentimetresArg = args[4] as Long
                        api.writeExerciseSession(
                            guideNameArg,
                            startTimeMillisArg,
                            endTimeMillisArg,
                            stepsArg,
                            distanceCentimetresArg
                        ) { result: Result<Boolean> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}
